### ISSUE TITLE
UI bugs (iOS 12)

### ISSUE THREAD

**Issue by CanerKaraca23** [zbrateam/Zebra#1173]
**Description**
iOS 12 and below UI Issues

**Device Informations:**
 - iOS Version: iOS 12.5.1
 - Zebra Version: Zebra 1.1.15
 - Device Type: iPhone 5S
 - Jailbreak Type: Chimera

**Bugs:**

- Dark/Ligh Mode switching problems on Changes Tab. [(Screenshot)](https://media.discordapp.net/attachments/570634688813858820/822109490303860766/image0.png)
- No/wrong selection colors for system wide. [(Video)](https://cdn.discordapp.com/attachments/572784833714192395/705455864827609088/video0.mp4) [(Video)](https://media.discordapp.net/attachments/446721039884353537/716264665293914153/video0.mp4) [(Video)](https://media.discordapp.net/attachments/446721039884353537/716264638807015504/video0.mp4)
- Dark mode isn't applied to the 3D touch menus. (by gkeep) [(Screenshot)](https://i.hizliresim.com/BbWvvx.jpg)

**Comment by CanerKaraca23** [comment]
![209A7E95-A671-4020-8999-93A0ABA60966](https://user-images.githubusercontent.com/37447503/80851993-9e91e580-8c2d-11ea-9822-227653fcd49f.png)
More UI bugs...

**Comment by CanerKaraca23** [comment]
![812737AA-F4E5-459E-BC96-532DC9756B95](https://user-images.githubusercontent.com/37447503/80891477-fa5f7b80-8ccc-11ea-9eed-c9138330ddc0.png)
![7DB48984-A4D4-4F5C-8E5E-30CB3B408F96](https://user-images.githubusercontent.com/37447503/80891480-fe8b9900-8ccc-11ea-9224-04bcbd992322.png)

**Comment by CanerKaraca23** [comment]
![E57D9311-8A88-45E9-881B-0330D3B0FF13](https://user-images.githubusercontent.com/37447503/80891519-2c70dd80-8ccd-11ea-87ac-3f5dc4009043.jpeg)
White clear button bug on Light Mode.

**Comment by CanerKaraca23** [comment]
![F2AEA842-007E-42F7-B55F-1736B3E42683](https://user-images.githubusercontent.com/37447503/81029741-c16f0480-8e8e-11ea-9d63-071c2930abc8.png)
White keyboard on multi repo adding screen.

**Comment by CanerKaraca23** [comment]
![1E49DBC8-0E12-4C17-96DB-2F2FB2A42AD2](https://user-images.githubusercontent.com/37447503/81110803-bb2b6780-8f24-11ea-8d6d-b0e2775681d7.png)
Black status bar on dark mode while selecting version.

**Comment by CanerKaraca23** [comment]
I'm having this issues on iOS 12.4.6/iPhone 5S/Zebra 1.1

**Comment by CanerKaraca23** [comment]
> I'm having this issues on iOS 12.4.6/iPhone 5S/Zebra 1.1
And they are the all UI issues on iOS 12 and possibly below I think. I didn't experienced more.

**Comment by CanerKaraca23** [comment]
Also 1, 5, 6 isn't transition issue.

**Comment by PoomSmart** [comment]
Some of the color issues fixed as of b801e5f62b7dd9adc7b926d8663ae58ebd71cd76

**Comment by PoomSmart** [comment]
Search result cells color issue fixed as of 5c795ae2c227b4025405a11c6ca81e1427e5f0a6

**Comment by PoomSmart** [comment]
Keyboard color for Add Multiple in Sources tab fixed as of b8ae34f2a6a04f1238f884bed993c8120032c1c0

**Comment by CanerKaraca23** [comment]
> Some of the color issues fixed as of [b801e5f](https://github.com/wstyres/Zebra/commit/b801e5f62b7dd9adc7b926d8663ae58ebd71cd76)

Which screenshots/videos are fixed now?

**Comment by PoomSmart** [comment]
You have 4 screenshots. I am certain the first three are fixed. The fourth one I could reproduce few times and did not see it anymore possibly due to code changes about refactoring theme that I lost track.

**Comment by CanerKaraca23** [comment]
I edited all thanks. Also there is an issue with color selection for Sources/Packages here. You can see the first post on this topic, I uploaded a video.

**Comment by PoomSmart** [comment]
See if 1.1.1 resort your last bug.

**Comment by CanerKaraca23** [comment]
Looks like black status bar while version selecting on dark mode still not fixed on 1.1.1
![9B46EF6C-E888-4622-A75E-D0F3490823DB](https://user-images.githubusercontent.com/37447503/81587523-d0d6dc00-93bf-11ea-96fc-ebe529f59094.png)

**Comment by CanerKaraca23** [comment]
![7ADB36BD-31BF-479A-B00B-4B0C47CE03FA](https://user-images.githubusercontent.com/37447503/81805606-dbaa8180-9523-11ea-8f6e-609cc1a2202c.png)
Still not fixed. This issue sometimes occurs and this is not a transition issue.

**Comment by CanerKaraca23** [comment]
@PoomSmart

**Comment by CanerKaraca23** [comment]
Not only status bar, there is 3 more issues here.

**Comment by CanerKaraca23** [comment]
I can confirm, Black status bar on dark mode while selecting version is fixed on 1.1.8 and 3 issues left.

**Comment by CanerKaraca23** [comment]
![B18F35E9-E2DD-440B-BA0F-94EBB16CF4AC](https://user-images.githubusercontent.com/37447503/82745025-6727dc00-9d88-11ea-9883-5f8c8bd7572b.png)
Install button location bug. Maybe its not bug.

**Comment by PoomSmart** [comment]
1.1.9 should fix the first of your latest Not Fixed list.

**Comment by CanerKaraca23** [comment]
I didn't see this issue on 1.1.9 anymore. Thanks! Also can you look this Screenshot up there?

**Comment by wstyres** [comment]
@CanerKaraca23 If you mean the install button then I'm not sure if that is actually a bug with Zebra or a bug with iOS.

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 If you mean the install button then I'm not sure if that is actually a bug with Zebra or a bug with iOS.

I think install button/other buttons is located wrong, should locate a little bit to right.

**Comment by CanerKaraca23** [comment]
![6C7751B3-9BAD-4D52-9C71-F5C4C541942D](https://user-images.githubusercontent.com/37447503/82829112-2977a000-9ebb-11ea-9126-9b9ce613857f.png)
Looks like still occurs.

**Comment by CanerKaraca23** [comment]
@PoomSmart

**Comment by gkeep** [comment]
Also, Dark Mode is not applied to the 3D touch menus.

![image](https://user-images.githubusercontent.com/20600053/82838663-913ae480-9ed5-11ea-9f26-694d57def838.jpeg)

**Comment by CanerKaraca23** [comment]
Added new 2 issues.

**Comment by PoomSmart** [comment]
> ![6C7751B3-9BAD-4D52-9C71-F5C4C541942D](https://user-images.githubusercontent.com/37447503/82829112-2977a000-9ebb-11ea-9126-9b9ce613857f.png)
> Looks like still occurs.

bf4df980fc29e3e90d249077fc5411303948db1d

**Comment by CanerKaraca23** [comment]
> > ![6C7751B3-9BAD-4D52-9C71-F5C4C541942D](https://user-images.githubusercontent.com/37447503/82829112-2977a000-9ebb-11ea-9126-9b9ce613857f.png)
> > Looks like still occurs.
> 
> [bf4df98](https://github.com/wstyres/Zebra/commit/bf4df980fc29e3e90d249077fc5411303948db1d)

Thanks!

**Comment by PoomSmart** [comment]
See if search clear button will be fixed in the next 1.1.x release.
83e04235e1e46fda331666fb345374aebec40b86

**Comment by CanerKaraca23** [comment]
Edited.

**Comment by CanerKaraca23** [comment]
Zebra really having issues with selection colors on iOS 12 Here videos:


https://media.discordapp.net/attachments/446721039884353537/716264665293914153/video0.mp4
https://media.discordapp.net/attachments/446721039884353537/716264665293914153/video0.mp4

**Comment by CanerKaraca23** [comment]
Updated.

**Comment by wstyres** [comment]
See https://github.com/zbrateam/Zebra/issues/1331#issuecomment-848384811
